list_of_numbers = [17, 38, 10, 25, 72]
sortedList = list_of_numbers.copy()
sortedList.sort()
print(sortedList)
list_of_numbers.append(12)
list_of_numbers.reverse()
print(list_of_numbers)
print(list_of_numbers.index(17))
list_of_numbers.remove(38)
print(list_of_numbers)
print(list_of_numbers[1:3])
print(list_of_numbers[:2])
print(list_of_numbers[2:])
print(list_of_numbers[:])
print(list_of_numbers[-1])